
#cyclic rotation is defined by chopping off a suffix from the end of Text and appending 
#this suffix to the beginning of Text. Next — similarly to suffix arrays 
#— order all the cyclic rotations of Text lexicographically to form a |Text| × |Text| matrix of symbols


Text = 'TAAGATCTACCGTGTATCCCCATGTCCCCTGCGGTTTCAAAGTCATAATCAGTATTGCTTGTCCAATACATGTCTTTAAATCCGGAACCTTCACTCCACCTCTATAATTCATACGGGTCGTCCCTACCTCCCTGAGATTTAATGTACTTCTGCCCGTAAAACAGCCCAAAGGACTATCAAGGACAACAAAATATACGACACCCAAAATCTGACAGACTACCATTACAATCGCACTAGAGTGGATAGGCTGCTAGGAAGAACGCCTCCGTGCAGACGAAGGAAATTTGAGGGAACTTTGCGCTAGATCAACAAACCTCTCCGTTTTAGATCACAAGCTTGCACTCTTAAATTTGCTAACCTTGTCAAGAGGACGGTGTAAAAGCGCAGGATTAACGCCTGTGAATCCTCCAATTGCGTACGGGGACTGGGTTTTGTCCATCGTGGGGCCGATAAATGTCCTCAAGGTTTATTCTTATTTAGGGGATGGGGGTGCGTCCATGTAATTCATACAAGGTGGTTGCAGAACCGGGTAAATAGCGGGAAATGAGTTAGCCGCGTTGTAGAGACGAAAAGCTTGCGCTTTTAGTAGCAAGAGTCCCCTATACAGATGGGGACTGGCCCTAAGGAAGCTGAGCCAAAGAGAGCTGTGCCCGAGAGCGTCGTGTTGTCTCCCTCGTGGACATTAAAGTCGCCCCAACCAATTTGGCCAAGCACTTGTCTTGTAGCGGGGTCGGGAGCGCCATGCCGGGATCAAATAGATCCGGACAAAACGTTGGCTAGGCTTGAGCAAGCTTCGTCGCTATTTTCTAATTGGAATTGGCCCCTGCGTTCCCCCATTGTACCCACAGCGCTGCTACGACACAGCTCAGTGAAGATTGAGACCTTC$'

def BWT(Text):
    x, y = [], [] 
    for i in range(len(Text)):
        x.append(Text[i:])
        y.append(i)
    y = sorted([Text[i:] + Text[:i] for i in range(len(Text))]) #cyclic rotations
    bwt = ([Text[-1] for Text in y])
    return bwt

print (''.join(BWT(Text)))